name: Android Build

on:
  workflow_dispatch:

jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib setup android
          haxelib install hxcpp 4.3.2 > nul
          haxelib install lime 8.1.1
          haxelib install openfl 9.2.2
          haxelib install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.10.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install away3d
          haxelib install hxvlc 1.4.1
          haxelib install flxanimate 3.0.4
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib install hscript 2.5.0
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib run lime rebuild hxcpp
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Set Haxelib Versions
        run: |
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.5.0
          haxelib set flixel 5.2.2
          haxelib set lime 8.1.1
          haxelib set openfl 9.2.2
          haxelib set hscript 2.5.0
          haxelib set hxvlc 1.4.1
          haxelib set hxcpp 4.3.2
          haxelib set flxanimate 3.0.4
      - name: Compile
        run:
         haxelib run lime build android -final
      - name: Publish Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: buildAndroid
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error